	<h3><i class="fas fa-list-alt"></i> Notre catalogue compte <?= $nombre['0']['COUNT(*)']?> espèces d'algues</h3>
	<p>Selon la littérature scientifique et certaines estimations, les eaux de La Réunion compteraient au moins un millier d'espèces d'algues : des macros, des micros, des cyanobactéries... Mais pour l'heure, ce compartiment du vivant est encore peu connu. Nous visons à améliorer la connaissance dans ce domaine avec ce catalogue. Vous pouvez nous y aider en ajoutant vos observations. Il suffit pour cela de vous créer un compte <a href="createUser.php">ici</a>. Vous pouvez également consulter toutes les espèces déjà recensées dans ce catalogue.</p>
	<section>
		<div class="catalogue">
			<article class="green">
				<h4>Les algues vertes</h4> 
				<figure>
					<img src="public/images/boergesenia-forbesii.jpg" alt="Forbesii">
				</figure>
				<p>Les Chlorophytes sont en principe de couleur verte. Elles peuvent prendre pourtant des couleurs plus sombres lorsque leurs cellules contiennent des éléments particuliers comme les carotènes, ou sous l’effet de l’ensoleillement jaunir ou brunir. Pérennes ou saisonnières, certaines d’entre elles sont connues pour proliférer sous le terme de « marées vertes » surtout quand l’eau est plus chaude et plus chargée en nutrients (azote, phosphore). On parle alors de « bloom algal ». Les ulves sont mondialement connues pour provoquer ce type de phénomène, lequel peut affecter la vie marine par sur-consommation de l’oxygène contenu dans l’eau la nuit. A la Réunion, d’autres espèces comme les caulerpes ont en 2007 proliféré, puis disparu sous l’effet d’une houle cyclonique. Depuis, quelques observations de ce type ont été répertoriées.
				Mais les causes précises du bloom reste encore mal comprises et pas toujours le signe d’une pollution directe. <a href="https://fr.wikipedia.org/wiki/Algue_verte">Allez voir wikipédia.</a>
				</p>
				<a class="btn" href="showAlgues.php?id=1">La liste</a>
			</article>
			<article class="red">
				<h4>Les algues rouges</h4>
				<figure>
					<img src="public/images/asparagopsis.jpg" alt="Asparagopsis">
				</figure>
				<p>Les Rhodophytes ont des complexes de pigments variés dont la qualité et la quantité varient selon leur situation plus ou moins profonde. En terme de diversité spécifique, ce sont les algues rouges qui sont les plus représentées dans les différents habitats marins de l’île car elles s’adaptent à beaucoup plus de conditions environnementales (lumière, nutrient, hydrodynamisme) que les algues vertes ou brunes.
				Sous l’océan de la Réunion, la présence d’algues rouges a été notée jusque -60m de profondeur sur les pentes sous-marines du volcan Piton de la Fournaise.
				Plusieurs espèces sont cultivées dans le monde pour être ensuite consommées directement ou utilisées par les industries agroalimentaires, cosmétiques, pharmacologiques. <a href="https://fr.wikipedia.org/wiki/Rhodophyta">Allez voir wikipédia.</a>
				</p>
				<a class="btn" href="showAlgues.php?id=2">La liste</a>
			</article>
			<article class="marron">
				<h4>Les algues brunes</h4>
				<figure>
					<img src="public/images/hydroclathrus-clathrus.jpg" alt="Hydroclathrus">
				</figure>
				<p>Les Phaeophytes prennent leur couleur brune dans la présence en plus de la chlorophylle d’un pigment particulier : la fucoxanthine. Elles peuvent avoir de grandes tailles comme le sont les sargasses par exemple. Globalement, on trouve des algues brunes près de la surface de l’océan, et en particulier dans les zones soumises au balancement des marées et à une forte agitation. Dans certaines régions, elles ont été rapportées comme proliférant et nuisant à la santé des autres peuplements, par exemple en Polynésie où les Turbinaria gênaient le développement des coraux bioconstructeurs.
				L’industrie alimentaire & cosmétique utilise plusieurs espèces en abondance car elles produisent des alginates et des caraghénanes en grande quantité. <a href="https://fr.wikipedia.org/wiki/Phaeophyceae">Allez voir wikipédia.</a> 
				</p>
				<a class="btn" href="showAlgues.php?id=3">La liste</a>
			</article>
			<div class="float"></div>
		</div>
	</section>
	<section class="mosaique last">
		<ul>
			<li><img src="public/medias/mosaique/boergesenia-forbesii" alt="Boergesenia forbesii"></li>
			<li><img src="public/medias/mosaique/caulerpa-webbiana.jpg" alt="Caulerpa webbiana"></li>
			<li><img src="public/medias/mosaique/galaxaura.jpg" alt="Galaxaura"></li>
			<li><img src="public/medias/mosaique/liagora.jpg" alt="Liagora albicans"></li>
			<li><img src="public/medias/mosaique/turbinaria-ornata.jpg" alt="Turbinaria ornata"></li>
			<li><img src="public/medias/mosaique/sargassum.jpg" alt="Sargassum"></li>
		</ul>
	</section>
	
	