<h2><i class="fas fa-cogs"></i> Administration</h2>

<h3><i class="fas fa-eraser"></i> Extraire les coordonnées d'une algue</h3>
<form class="modif-form" action="processExtractCoord.php" method="POST">

    
	<label>Nom</label>
	<input type="text" value="<?=$algue['name']?>">
	<label>Pour quelle algue vérifiée ?</label>
	<input type="hidden" name="lat" value="<?=$algue['latitude']?>">
	<input type="hidden" name="long" value="<?=$algue['longitude']?>">


	<select name="id_algue">
<?php foreach($listAlguesVerif AS $key=>$algue):?>
	
		<option value="<?=$algue['id_algue']?>"><?=$algue['name']?></option>
<?php endforeach ?>
	</select>
	<label>Les coordonnées à sauvegarder</label>  
	<div id="map"></div>
	<div type="hidden">
		<script> var result = <?php echo($json); ?>;
		console.log(result);
		</script>
	</div>

	  
	<div class="envoi">
		<button class="btn-submit">Valider</button>
		<button class="btn-reset" type="reset">Annuler</button>
	</div>
</form>
<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
   integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
   crossorigin=""></script>
<script type="text/javascript" src="public/js/mapShow2.js"></script>
