		
	</main>
		<footer>
			<nav>
				<ul class="nav-footer">
					<li>
						<a href="whoWeAre.php"><i class="fas fa-building"></i>Qui sommes nous ?</a>
					</li>
					<li>
						<a href="contact.php"><i class="fas fa-envelope-square"></i>Contact</a>
					</li>
					<li>
						<a href="#"><i class="far fa-copyright"></i>Crédits et politique de confidentialité</a>
					</li>
				</ul>
			</nav>
		</footer>
	</body>
</html>