<h3><i class="fas fa-hands-helping"></i> Renseigner une algue</h3>


<fieldset>
	<legend class="legend">Description</legend>
	<form class="form" method="POST" action="processAdd.php" enctype="multipart/form-data">
		<ul>
			<li>
				<input type="hidden" name="id_author" value="<?php echo($_SESSION['user']['id_user']); ?>">
			</li>
			<li>
				<label for="date">Date de l'observation <span>*</span></label>
				<input type="date" id="date" name="observed_at" min="1990-01-01" max="2020-04-30" required="required">
			</li>
			<p id="error_date"></p>
			<li>
				<label class="label_fichier" for="mon_fichier">Fichier (format JPG | max. 1 Mo) <span>*</span></label>
     				<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
     				<input type="file" name="mon_fichier" id="mon_fichier" accept=".jpg, .jpeg" required="required" />
     				<p class="preview">Aucun fichier sélectionné</p> 
     		</li>
     			
			<li>
			     <label for="title_photo">Titre du fichier (max. 50 caractères) <span>*</span></label>
			     <input type="text" name="title_photo" id="title_photo" required="required">
			     	
			</li>
			<p id="previewTitlePhoto"></p>
			<li>
				<label for="profondeur">A quelle profondeur ?<span> *</span></label>
				<select id="profondeur" name="profondeur" required="required">
					<option value="">Je ne sais pas</option>
					<option value="sur la berge">Sur la berge</option>
					<option value="en surface">En surface</option>
					<option value="de 0 à 5m">Entre 0 et 5 m</option>
					<option value="de 5 à 10m">Entre 5 et 10 m</option>
					<option value="de 10 à 20m">Entre 10 et 20</option>
					<option value="de 20 à 30m">Entre 20 et 30 m</option>
					<option value="de 30 à 40m">Entre 30 et 40 m</option>
					<option value="plus de 40m">Au-delà de 40 m</option>
				</select>
			</li>
			<li>
				
				<label>A quel endroit ?<span> *</span></label>  
  				  
  				
  				  <div id="map">
  				  </div>
									 
  				  <input type="hidden" id="lat">
  				  <input type="hidden" id="long">

			</li>
			<p id="previewCoord"></p>
			<li>
				<label for="category">A votre avis, à quelle catégorie appartient votre algue ? <span> *</span></label>
				<select id="category" name="category_id" required="required">	
					<option value="">Aucune idée</option>
					<option value="4">Je ne sais pas</option>
					<option value="1">Verte</option>
					<option value="2">Rouge</option>
					<option value="3">Brune</option>
				</select>
			</li>

			<li>
				<label for="name">Connaissez-vous son nom ?</label>
				<input type="text" id="name" name="name">
			</li>
			<li>
				<label for="description">Faites-nous une description sommaire du lieu et de son aspect</label>
				<textarea rows="10" cols="78" id="description" name="description"></textarea>
			</li>
			


<?php if (!empty($_SESSION['user']) AND $_SESSION['user']['habilitation'] === 'admin'):?>
			<li>
				<label for="utilisation">Quels possibles usages ?</label>
				<textarea id="utilisation" name="utilisation"></textarea>
			</li>
			<li>
				<label for="url_info">Fiche wikipédia</label>
				<textarea id="url_info" name="url_info"></textarea>
			</li>
<?php endif ?>

		</ul>
		<p id="asterisque">Les champs marqués par un (*) sont obligatoires.</p>	
		<div class="envoi">
			<button id="subalgues" class="btn-submit" type="submit">Envoyer</button>
			<button class="btn-reset" type="reset">Annuler</button>
		</div>
		
	</form>
</fieldset>
 <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
   integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
   crossorigin=""></script> 
<script src="public/js/donnees.js"></script>
<script src="public/js/functions.js"></script>
<script src="public/js/map.js"></script>
<script src="public/js/soumission.js"></script>