
	<section class="intro">
			<h2><span>Le monde des algues </span> : un territoire à défricher à La Réunion</h2>
			<figure>
				<div id="slidehome">
					<ul id="sContent">
						<li><img class="img-right" src="public/images/plateaualgal.jpg" alt="Plateau algale de Sargassum">
						</li>
						<li>
							<img class="img-right" src="public/images/anadyomene-wrighti-home.jpg" alt="Algue Anadyomene wrighti" />
						</li>
					</ul>
				</div>
			</figure>

			<p>Nous avons conçu ce site, que nous avons baptisé De Natur'algae, pour partager les connaissances sur la biodiversité marine algale de La Réunion. Les algues sont en effet désormais reconnues comme une filière du futur (<a href="https://adebiotech.org/home/img/algues/LIVRE_TURQUOISE-V.screen.pdf">lien vers l’ouvrage</a>).
			L’objectif premier est, grâce à l’action de chacun des collaborateurs, qu’il soit scientifique, photographe ou simple citoyen d’intégrer cette démarche de science participative. Pour collaborer, il vous suffit de vous créer un compte <a href="createUser.php">ici</a>.</p>
			<p>Dans cette première version du site, nous focalisons nos efforts sur les algues du « lagon », et dans un second temps avec votre collaboration il sera possible de partager l’information sur la biodiversité des zones en dehors des lagons, notamment les pentes externes récifales.
			Dans le contexte du réchauffement climatique, une attention particulière est maintenant nécessaire pour certaines algues, qui sont ou seraient indicatrices d’un changement climatique, d’une prolifération soudaine ou encore d’une invasion extérieure.
			Hormis les cyanobactéries, que l’on dénommait auparavant « algues bleues » qui ne sont pas traitées ici, à la Réunion, il a été observé dans le passé récent plusieurs évènements de prolifération d’algues, qui ont essentiellement concerné des algues vertes (Caulerpa, Boodlea, Ulva).
			</p>
			<p>
			Les algues qui recouvrent les coraux morts (épiphytes), méritent également une attention mais leur petite taille et la complexité d’identification taxonomique limite fortement la capacité à les présenter ici. Qu’ils soient morts récemment (par exemple des suites néfastes d’un blanchissement corallien sévère) ou sous la forme de blocs coralliens, c’est en fait un complexe multispécifique qui est présent que l’on nomme sous le terme de « turf algal ».
			Ce turf est particulièrement bien visible en lagon, sur les parties nécrosées des coraux branchus ou submassifs et devient le territoire farouchement gardé par les demoiselles « jardinières)
			</p>
			<p>
			Il n’existe pas à la Réunion de programme dédié au suivi des communautés de macroalgues mais dans le cadre des réseaux de surveillance, il est tenu compte de leur abondance relative. A côté du programme scientifique expert porté par la Réserve marine, il existe Reef Check, le programme mondial de science participative sur la santé des récifs coralliens, qui est un outil citoyen pour suivre les coraux, les poissons-papillon mais aussi les grandes catégories d’algues. <a class="lien" href="https://www.reefcheck.fr/reunion/"> En savoir plus sur Reef Check à la Réunion</a>.
			</p>
			<div class="clear"></div>
	</section>
	<section class="enviro">
			<h2>L'environnement marin réunionnais</h2>
			<div>
				<figure>
						<figcaption>Carte de localisation des récifs de La Réunion (source : Vie Océane)</figcaption>
						<img src="public/medias/images/carte.jpg" alt="Carte du lagon de La Réunion">
						
				</figure>
			
				
				<p>A La Réunion, île au volcanisme encore actif dans le sud-est, les habitats marins côtiers sont essentiellement dominés par des substrats durs de type rocheux (basaltique) ou corallien. Il existe également des zones sableuses associées à ces deux types, mais qui n’abritent que de rares espèces d’algues.
				Les récifs de La Réunion forment une ceinture discontinue à l’ouest et au sud-ouest. C’est globalement le littoral compris entre Saint-Pierre au sud et le Cap La Houssaye au nord, car ce secteur de l’île bénéficie de conditions météorologiques plus favorables aux coraux (soit 25 km), mais tous les récifs ne sont pas actuellement parties intégrantes de la Réserve naturelle marine de La Réunion qui assure de nombreuses missions de surveillance et de connaissances (<a href="http://www.reservemarinereunion.fr">en savoir plus</a>).
				</p>
				<p>Les récifs occupent une superficie globale de 18 km2 (évaluation 2015) et peuvent être divisés schématiquement en deux types : les pentes externes qui sont la zone battue par la houle et « le lagon » qui est l’espace protégé de la houle par la barrière corallienne. Il existe, car l’île est jeune, des récifs embryonnaires où cohabitent coraux, invertébrés, algues, …).
				Dans le lagon, il est aisé de séparer plusieurs zones depuis la plage jusqu’à la barrière : d’abord la dépression d’arrière lagon (le lagon) qui peut être sableuse ou avec des pâtés coralliens plus ou moins riches et diversifiés en faune (et flore), puis le platier qui débute la barrière récifale et qui est bien exposé à l’action des houles, mais peut à marée basse émerger et donc souffrir d’un excès de soleil ou d’eau pluviale.
				</p>
				<p>Plus de 2800 espèces de faune et de flore marine ont été inventoriés depuis que les scientifiques réalisent des expertises. Ce chiffre reflète en réalité des disparités assez grandes dans le niveau de connaissance des groupes. Dans les lagons de la Réunion, la biodiversité marine animale (et végétale dans une moindre mesure) est désormais bien connue et partagée avec les citoyens notamment via le site Wikipédia dédié (<a href="https://fr.wikipedia.org/wiki/Biodiversit%C3%A9_marine_des_lagons_de_La_R%C3%A9union">Lien ici</a>). Celui des algues a fait l’objet de travaux de recherche dès les années 1980 (par exemple Payri en1985 ; Naim en 1997), car des phénomènes de dégradation importants étaient constatés. Historiquement, on retrouve comme référence les travaux de Jadin en 1935. Plus récemment, des travaux menés sur les pentes sous-marines du Piton de la Fournaise ainsi que dans les zones récifales, ont été publiées (Zubia et al, 2017 : Zubia et al., 2018).
				</p>
				Ce sont ces deux habitats principaux (le lagon et la pente externe) qui sont priorisés et pour lesquels un travail d’inventaire de la biodiversité des algues est fait.
				Avec une attention particulière pour les espèces qui peuvent s’avérer envahissantes comme les caulerpes, les Asparagopsis, les ulves, les Boodlea...
				</p>				
			</div>
			<div>
				<figure>
						<img src="public/medias/images/lagon.jpg">
				</figure>
				<figure>
						<img src="public/medias/images/lagon3.jpg">
				</figure>
			</div>
	</section>

	<section class="last">
	
		<h2>Trois grandes nuances de couleurs d'algues</h2>
		<p>Du point de vue scientifique et en écartant ici les cyanobactéries encore appelées algues bleues, trois grands groupes dénommés « algues vertes », « algues brunes » et « algues rouges » (les classes du point de vue taxinomique) constituent la flore algale qui peut occuper tous les types de milieux compris sous l’océan mais aussi en dehors, là où l’humectation des vagues permet leur développement.
		Outre la couleur, c’est avec la forme qu’il est également possible au débutant ou à l’amateur éclairé de progresser dans la connaissance du monde des algues marines, par exemple les espèces encroûtantes, les espèces dressées, les espèces calcifiées...
		Hormis quelques observations particulières d’algues flottant en surface de l’océan Indien autour de La Réunion, la plupart des macroalgues marines se développent en se fixant sur un substrat (on dit qu'elles sont sessiles).
		</p>
		<div class="catalogue">

			<article>
				<h4>Les algues vertes</h4> 
				<figure>
					<img src="public/images/boergesenia-forbesii.jpg" alt="Forbesii">
				</figure>
				<p>
					Les Chlorophytes sont en principe de couleur verte. Elles peuvent prendre pourtant des couleurs plus sombres lorsque leurs cellules contiennent des éléments particuliers comme les carotènes, ou sous l’effet de l’ensoleillement jaunir ou brunir. Pérennes ou saisonnières, certaines d’entre elles sont connues pour proliférer sous le terme de « marées vertes » surtout quand l’eau est plus chaude et plus chargée en nutrients (azote, phosphore). On parle alors de « bloom algal ». Les ulves sont mondialement connues pour provoquer ce type de phénomène, lequel peut affecter la vie marine par sur-consommation de l’oxygène contenu dans l’eau la nuit. A La Réunion, d’autres espèces comme les caulerpes ont en 2007 proliféré, puis disparu sous l’effet d’une houle cyclonique. Depuis, quelques observations de ce type ont été répertoriées.
					Mais les causes précises du bloom reste encore mal comprises et pas toujours le signe d’une pollution directe. <a href="https://fr.wikipedia.org/wiki/Algue_verte">Sur wikipédia.</a>
				</p>
				<a class="btn" href="showAlgues.php?id=1">La liste</a>
				<div class="clear"></div>
			</article>
			<article>
				<h4>Les algues rouges</h4>
				<figure>
					<img src="public/images/asparagopsis.jpg" alt="Asparagopsis">
				</figure>
				<p>Les Rhodophytes ont des complexes de pigments variés dont la qualité et la quantité varient selon leur situation plus ou moins profonde. En terme de diversité spécifique, ce sont les algues rouges qui sont les plus représentées dans les différents habitats marins de l’île, car elles s’adaptent à beaucoup plus de conditions environnementales (lumière, nutrient, hydrodynamisme) que les algues vertes ou brunes.
				Sous l’océan de La Réunion, la présence d’algues rouges a été notée jusque -60m de profondeur sur les pentes sous-marines du volcan Piton de la Fournaise.
				Plusieurs espèces sont cultivées dans le monde pour être ensuite consommées directement ou utilisées par les industries agroalimentaires, cosmétiques ou pharmacologiques. <a href="https://fr.wikipedia.org/wiki/Rhodophyta">Sur wikipédia.</a>
				</p>
				<a class="btn" href="showAlgues.php?id=2">La liste</a>
			</article>
			<article>
				<h4>Les algues brunes</h4>
				<figure>
					<img src="public/images/hydroclathrus-clathrus.jpg" alt="Hydroclathrus">
				</figure>
				<p>Les Phaeophytes prennent leur couleur brune dans la présence en plus de la chlorophylle d’un pigment particulier : la fucoxanthine. Elles peuvent avoir de grandes tailles comme le sont les sargasses par exemple. Globalement, on trouve des algues brunes près de la surface de l’océan, et en particulier dans les zones soumises au balancement des marées et à une forte agitation. Dans certaines régions, elles ont été rapportées comme proliférant et nuisant à la santé des autres peuplements, par exemple en Polynésie où les Turbinaria gênaient le développement des coraux bioconstructeurs.
				L’industrie alimentaire et cosmétique utilise plusieurs espèces en abondance car elles produisent des alginates et des caraghénanes en grande quantité. <a href="https://fr.wikipedia.org/wiki/Phaeophyceae">Sur wikipédia.</a> 
				</p>
				<a class="btn" href="showAlgues.php?id=3">La liste</a>
			</article>
		</div>
		<div class="clear"></div>
	</section>
	

