


<h3>Dans la liste des <?= $algue['category_name']?></h3>

<section id="onealgue">
	<h4><?= $algue['name']?></h4>
	<article>
		<div id="oneAlgue">		
			<figure>
				<img src="<?= $algue['image_url'] ?>">
				<figcaption>Photo : <?= ucfirst($algue['firstname']) . " " . ucfirst($algue['lastname']) ?>.
				</figcaption>
			</figure>

			<div id="map"></div>
			<div type="hidden">
				<script> var result = <?php echo($json); ?>;</script>
	  		</div>
		</div>
		<div>
			<p><?=$algue['description']?></p>
	<?php if(isset($algue['url_info'])):?>
			<p>Si vous voulez en savoir davantage sur cette espèce, le net compte des ressources comme <a href="<?=$algue['url_info']?>" class="lien">ici</a></p>
	<?php endif ?>
		</div>	
		
	</article>
	
	<a class="btn" href="catalogue.php">Retour</a>
	<div class="clear"></div>
</section>

<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
   integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
   crossorigin=""></script>
<script type="text/javascript" src="public/js/mapShow2.js"></script>
