<h3><i class="fas fa-building"></i> Qui sommes nous ?</h3>
<section class="last">
  
  <h2>La vie sous-marine ? Nous on l’aime, on la protège.</h2>

  <p>DeNaturAlgae, un drôle de nom pour ce site qui est un projet de science participative et citoyenne destiné à partager des connaissances avec ceux qui - comme nous (photographes naturalistes, d’amateurs éclairés en écologie marine, d’étudiants en science de la Vie...) - ont à cœur de mieux connaître et protéger la biodiversité marine de La Réunion.
     « Connaître pour protéger et gérer », telle est la devise de l’équipe de ce projet à but non lucratif et non commercial. Notre équipe est constituée de spécialistes de la biologie marine et de la communication.
     Notre rêve ? Que grâce à chacun de vous, la base de données sur les algues de La Réunion soit rapidement étendue à l’ensemble de l’île et que ces connaissances participent à mieux gérer les écosystèmes marins.</p>
</section>